### PR TITLE
Result improvement

### PR DESCRIPTION
**Pull request by uhtna**
Preliminary edits. Syntax may be completely wrong, will test with Storybook later today. Ignore changes to Survey.jsx.

### CODE REVIEW

**Comment by VulpesVulpes825** [comment]
Make sure you rebase your codebase, so you will not have conflict when merge.

**Comment by VulpesVulpes825** [comment]
> Ignore changes to Survey.jsx.
Then you should not commit Survey.jsx. Make sure you remove the change by amending the commit.

**Comment by uhtna** [comment]
Sorry my mistake. I am still learning how to use git. I accidentally clicked the review button.

**Comment by VulpesVulpes825** [comment]
No worries. But please fix the issue I mentioned by Friday's meeting.

**Pull request closed without merging**
