### PR TITLE
Timeline test branch 2

### PR DESCRIPTION
**Pull request by ctuguinay**
This is all on a very old branch of the project. I still need so work on some stuff; I still can't seem to get the array to show on the Homepage where I am testing it on. I also need to pull and update my entire personal repository to match the current project. 

It appears as though I didn't do much and that is very much true. I spent most of my time getting familiar with the project and learning how to actually test my function component. I did most of this using antd and switched to bootstrap recently after being told that I shouldn't use antd. I just tried to use a simple grid (col/row) to show the array contents of events and I'll try to make it more fancy once I can figure out my stubborn array problem.

I will have much more time to work on this during break and next quarter; I just have been super busy this quarter.

### CODE REVIEW

**Comment by VulpesVulpes825** [comment]
> I did most of this using antd and switched to bootstrap recently after being told that I shouldn't use antd.

I believe I have stressed this issue when I initially assigned the task to you four weeks ago, that antd code is only for reference.

> This is all on a very old branch of the project.

Also, why you are using uhtna's branch rather than the master branch, considering your changes is committed today.

**Comment by ctuguinay** [comment]
I had a lot of trouble for some reason running it on the current master branch last night. I had a lot of errors that I wasn't getting from very old versions and I wasn't able to test at all yesterday on the master branch. I will find a way to get it to work though. I believe it was an axiom import error and a prettier error.

**Comment by VulpesVulpes825** [comment]
> I had a lot of trouble for some reason running it on the current master branch last night.

That is strange, considering GitHub Action has successfully build and run the app without any issues. 
Try `docker system prune -a --volumes` to reset docker image. You can learn more about this command in [docker's doc](https://docs.docker.com/engine/reference/commandline/system_prune/)

**Comment by VulpesVulpes825** [comment]
> Try `docker system prune -a --volumes` to reset docker image. You can learn more about this command in [docker's doc](https://docs.docker.com/engine/reference/commandline/system_prune/)

I have also changed the `yarn dev:destroy` command to also delete docker images. 
Run `yarn dev:destroy`, pull the latest master branch, and run `yarn dev:start`. This should work as GitHub action pass the docker building test.

> There should be no axiom import error. It might be prettier error, meaning you did not fix your code style using prettier.

**Pull request closed without merging**
